import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Dancing_Script } from "next/font/google";
import { Merienda } from "next/font/google"; 
import "./globals.css";
import Header from "@/components/header";
import { Suspense } from "react";
import Loader from "@/components/loader";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${dancingScript.variable} ${merienda.variable}`}>
        <Header />
        <Suspense fallback={<Loader />}>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
